# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    enabled_locales: ['en']
    trusted_hosts:  ['^verspiel\.com$', '^localhost$']
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    rate_limiter:
        post_comment:
            policy: 'fixed_window'
            limit: 5
            interval: '2 minutes'
        username_change:
            policy: 'fixed_window'
            limit: 5
            interval: '24 hour'
        password_reset:
            policy: 'fixed_window'
            limit: 3
            interval: '24 hour'
        register:
            policy: 'fixed_window'
            limit: 2
            interval: '48 hour'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
