controllers:
    resource: ../src/Controller/
    type: annotation

api:
    resource: ../src/Controller/Api
    type: annotation
    prefix: api

api_token:
    resource: ../src/Controller/Api/Token
    type: annotation
    prefix: api/token

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/token/authenticate
