kernel:
    resource: ../src/Kernel.php
    type: annotation

controllers:
    resource: ../src/Controller/
    type: annotation

api:
    resource: ../src/Controller/Api
    type: annotation
    prefix: api

api_token:
    resource: ../src/Controller/Api/Token
    type: annotation
    prefix: api/token

api_login_check:
    path: /api/token/authenticate

admin:
    resource: ../src/Controller/Admin
    type: annotation
    prefix: admin
